In [2]:
# 1: Import the numpy package under the name np
import numpy as np

In [7]:
# 2: Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jonathan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/Jonathan/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jonathan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\wind

In [11]:
# 3: Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [16]:
# 4: How to find the memory size of any array
Z = np.zeros((10,10))
size = Z.size * Z.itemsize
print("Number of bytes is: " + str(size))

Number of bytes is: 800


In [17]:
# 5: How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
# 6: Create a null vector of size 10 but the fifth value which is 1
vector_q6 = np.zeros(10)
vector_q6[4] = 1
print(vector_q6)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [10]:
# 7. Create a vector with values ranging from 10 to 49

# My initial approach
num_elements = 49 - 10 + 1
vector_q7 = np.zeros(num_elements)
for i in range(num_elements):
    vector_q7[i] = i + 10

print(vector_q7)

# Utilizing NumPy methods
vector_q7v2 = np.arange(10,50)
print(vector_q7v2)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.
  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.
  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# 8. Reverse a vector (first element becomes last)
vector_q8 = np.arange(1,11)
vector_q8_reversed = np.flip(vector_q8, 0)
print(vector_q8_reversed)

[10  9  8  7  6  5  4  3  2  1]


In [9]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
vector_q9 = np.arange(0,9)
print(vector_q9)

matrix_q9 = np.matrix(vector_q9).reshape(3,3)
print(matrix_q9)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
vector_q10 = [1, 2, 0, 0, 4, 0]
result_q10 = np.nonzero(vector_q10)
print(result_q10)

(array([0, 1, 4], dtype=int64),)


In [18]:
# 11. Create a 3x3 identity matrix (★☆☆)
matrix_q11 = np.identity(3)
print(matrix_q11)

# can also use np.eye
matrix_q11_v2 = np.eye(3)
print(matrix_q11_v2)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [21]:
# 12. Create a 3x3x3 array with random values (★☆☆)
matrix_q12 = np.random.random((3,3,3))
print(matrix_q12)

# lets try the other "random" method
# Difference is due to different distribution of values
matrix_q12_v2 = np.random.random_sample((3,3,3))
print(matrix_q12_v2)

[[[ 0.80910257  0.24096351  0.42480066]
  [ 0.83175507  0.88352156  0.38430917]
  [ 0.56773391  0.49617722  0.86019714]]

 [[ 0.90402516  0.90030788  0.51312781]
  [ 0.43827137  0.49636101  0.63907195]
  [ 0.09009431  0.27658974  0.35630275]]

 [[ 0.08030828  0.6819835   0.67890131]
  [ 0.31789234  0.39727105  0.78677678]
  [ 0.27498073  0.16345308  0.80339986]]]
[[[ 0.14970146  0.48598253  0.93833039]
  [ 0.33206451  0.62058869  0.13797723]
  [ 0.83676247  0.23878651  0.01027566]]

 [[ 0.5929231   0.48251987  0.69701446]
  [ 0.00620826  0.51793023  0.5195254 ]
  [ 0.74644882  0.28111726  0.22399814]]

 [[ 0.56858892  0.22326253  0.21300308]
  [ 0.80350613  0.03745843  0.49527634]
  [ 0.96148312  0.2195392   0.46434224]]]


In [26]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
matrix_q13 = np.random.random((10,10))
print(matrix_q13)

max_value_q13 = np.amax(matrix_q13)
print(max_value_q13)

min_value_q13 = np.amin(matrix_q13)
print(min_value_q13)

# The min and max functions should be the same as the below
max_value_q13_v2 = matrix_q13.max()
print(max_value_q13_v2)

min_value_q13_v2 = matrix_q13.min()
print(min_value_q13_v2)

[[ 0.75718453  0.29845997  0.02714191  0.08340639  0.26204898  0.27589492
   0.33012986  0.25389114  0.1250062   0.82427293]
 [ 0.74613725  0.36060123  0.07893807  0.71678716  0.54966821  0.96323204
   0.98739353  0.8996259   0.49974503  0.69425737]
 [ 0.29036658  0.58060489  0.93701004  0.60168182  0.98382356  0.11625995
   0.27405714  0.9545247   0.505395    0.47175753]
 [ 0.81829232  0.28525687  0.60756334  0.03925809  0.51564935  0.42981101
   0.5722672   0.83499591  0.90948841  0.82447584]
 [ 0.77887719  0.70749111  0.68329956  0.37828839  0.25000173  0.28618789
   0.34231949  0.0032188   0.54063062  0.75749474]
 [ 0.4594221   0.81431904  0.49258477  0.9492174   0.96758374  0.30142264
   0.9614767   0.24831949  0.52226349  0.8312987 ]
 [ 0.72636821  0.72340201  0.97912442  0.00846998  0.57239352  0.27895537
   0.40512313  0.51325494  0.79168757  0.43596469]
 [ 0.73985733  0.03932933  0.61270736  0.41564639  0.38910294  0.58837413
   0.08546571  0.18422218  0.04050838  0.75945481]


In [30]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
vector_q14 = np.random.random(14)
vector_q14_mean = vector_q14.mean()
print(vector_q14_mean)

0.485741321423


In [36]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
n = 5
d = 5

matrix_q15 = np.ones((n,d))
print(matrix_q15)

matrix_q15[1:-1, 1:-1] = 0
print(matrix_q15)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [46]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
n = 4
d = 4

matrix_q16 = np.random.random((n,d))

# This was my "manual" way of doing it
matrix_q16[0,1:-1] = 0
matrix_q16[n-1,1:-1] = 0
matrix_q16[0:n,0] = 0
matrix_q16[0:n, d-1]= 0
print(matrix_q16)

# Utiliizing numpy, we can do:
matrix_q16_v2 = np.pad(matrix_q16_v2, pad_width=1, mode='constant', constant_values=0)
print(after_pad)

[[ 0.          0.          0.          0.        ]
 [ 0.          0.4171355   0.34446739  0.        ]
 [ 0.          0.73036882  0.18156937  0.        ]
 [ 0.          0.          0.          0.        ]]
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.57574711  0.68744169  0.881312    0.04368236  0.        ]
 [ 0.          0.66699556  0.89842223  0.0353257   0.23487434  0.        ]
 [ 0.          0.76762928  0.31675888  0.78220649  0.04065184  0.        ]
 [ 0.          0.15159785  0.62926247  0.18780962  0.86772998  0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


In [47]:
# 17. What is the result of the following expression? (★☆☆)
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1

# The results are
# nan
# false
# false
# nan
# true # This one is special because ******************************************************************************** TODO

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [52]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
matrix_q18 = np.zeros((5,5))
vector_q18 = np.arange(1,5)

matrix_q18 = np.diag(vector_q18, k=-1)

print(matrix_q18)

# Found out that np.diag() is for constructing a diagonal and np.diagonal() is for extracting diagonal values

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
